version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: >
      sh -c "
        echo 'Variables de entorno al iniciar:' &&
        env | grep HUGGING &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge